# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  build:
    name: Test
    runs-on: self-hosted
    strategy:
      matrix:
        node: ["16.13.0"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          clean: 'false'

      - name: Install Dependencies
        run: yarn install
        env:
          CI: true

      - name: Cypress run
        id: cy-run
        run: yarn cy:ci
    
    
      - name: Cypress Screenshot & Video Upload to WorkChat
        uses: SreeniIO/cypress-upload-to-workchat-action@v1.0.8
        if: failure() && steps.cy-run.outcome == 'failure'
        with:
          token: ${{ secrets.WORKPLACE_TOKEN }}
          channel: '4559984164046735'
          message-text: 'Cypress tests failed! They are being uploaded here, good luck.'
